import '@mantine/core/styles.css'
import { ColorSchemeScript, MantineProvider, createTheme } from '@mantine/core'
import { Metadata } from 'next'
import { BlitzProvider } from "@/blitz-client"
import { Inter } from "next/font/google"
import UserInfo from "@/components/UserInfo"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: {
    template: '%s | Testing Stack',
    default: 'Testing Stack',
  },
  description: "Generated by blitz new ",
}

const theme = createTheme({
  fontFamily: 'Open Sans, sans-serif',
  primaryColor: 'green',
})

export default function RootLayout ({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body className={inter.className}>
        <BlitzProvider>
          <MantineProvider theme={theme} defaultColorScheme="auto">
            <UserInfo />
            {children}
          </MantineProvider>
        </BlitzProvider>
      </body>
    </html>
  )
}

